### ISSUE TITLE
Exported video does not have transition

### ISSUE THREAD

**Issue by saba-anwar88** [alexiscn/MTTransitions#23] opened 2022-06-22 09:41 UTC
Hi

I'm using this library with swift. Video is well playing with AVPlayer but when I use MTVideoExporter to save video it does not contain transition, frames between video display as black screen. Any help will be appreciated

Thanks 
Saba

**Comment by saba-anwar88** [comment] 2022-06-22 09:47
<img width="593" alt="Screenshot 2022-06-22 at 2 46 19 PM" src="https://user-images.githubusercontent.com/81956581/174999021-15dd6ba2-abcb-4c4f-95af-27c7c6feb71e.png">

**Comment by saba-anwar88** [comment] 2022-06-22 09:48
<img width="566" alt="Screenshot 2022-06-22 at 2 47 45 PM" src="https://user-images.githubusercontent.com/81956581/174999270-219774b0-af05-4610-8aaf-9c505d6d2f18.png">

**Comment by alexiscn** [comment] 2022-06-24 00:12
can you provide a demo project ?

**Comment by saba-anwar88** [comment] 2022-06-25 00:05
[VidTransition.zip](https://github.com/alexiscn/MTTransitions/files/8983540/VidTransition.zip)


> can you provide a demo project ?

**Comment by alexiscn** [comment] 2022-06-25 02:16
> [VidTransition.zip](https://github.com/alexiscn/MTTransitions/files/8983540/VidTransition.zip)
> 
> > can you provide a demo project ?

You demo project exported video do contains the transition.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/1132546/175754455-57f8f2cd-e29a-49e7-a21c-9c67abc2b867.png">

**Comment by alexiscn** [comment] 2022-06-25 02:17
<img width="578" alt="image" src="https://user-images.githubusercontent.com/1132546/175754466-229f689c-c6f7-4e83-833d-ea11de281dfb.png">

**Comment by saba-anwar88** [comment] 2022-06-25 06:39
https://user-images.githubusercontent.com/81956581/175761680-22c75de4-761d-4e46-b74e-adfd6566a3ba.mp4

Please have a look on this video its not having transition. Let me know please which Xcode version you are using or what the reason it could be? I'm running the video on quick time player

**Comment by alexiscn** [comment] 2022-06-25 09:33
Xcode 13.4.1 and iOS 15.5

**Comment by alexiscn** [comment] 2022-07-13 08:59
I am closing this issue since I can not reproduce the issue.

**Closed by alexiscn** 2022-07-13 08:59 UTC
